# Generated by Django 4.2 on 2025-02-12 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('nickname_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 1')),
                ('nickname_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 2')),
                ('nickname_3', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 3')),
                ('nickname_4', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 4')),
                ('nickname_5', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 5')),
                ('nickname_6', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 6')),
                ('nickname_7', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 7')),
                ('nickname_8', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 8')),
                ('nickname_9', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 9')),
                ('nickname_10', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 10')),
            ],
            options={
                'verbose_name': 'Departament',
                'verbose_name_plural': '1.Цех',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('nickname_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 1')),
                ('nickname_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname 2')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.departament')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': '2.Отдел',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=255, verbose_name='Имя и Фамилия')),
                ('job_title', models.CharField(max_length=255, verbose_name='Должность')),
                ('number_1', models.CharField(max_length=255, verbose_name='Внутренний номер')),
                ('number_21', models.CharField(blank=True, max_length=255, null=True, verbose_name='Городской номер 1')),
                ('number_22', models.CharField(blank=True, max_length=255, null=True, verbose_name='Городской номер 2')),
                ('number_23', models.CharField(blank=True, max_length=255, null=True, verbose_name='Городской номер 3')),
                ('is_active_gorod_number', models.BooleanField(default=True, verbose_name='Показать городской номер')),
                ('number_31', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сотовый номер 1')),
                ('number_32', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сотовый номер 2')),
                ('number_33', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сотовый номер 3')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.departament', verbose_name='Цех')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': '3.Телефон номер',
            },
        ),
    ]
