# Generated by Django 4.2 on 2025-02-28 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='is_active_vnut_number',
            field=models.BooleanField(default=True, verbose_name='Показать внутренний номер'),
        ),
        migrations.AlterField(
            model_name='section',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.departament', verbose_name='Цех'),
        ),
    ]
