# Generated by Django 4.2 on 2025-02-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='depart',
        ),
    ]
