# Generated by Django 4.2 on 2025-02-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_phone_is_active_vnut_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departament',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
