# Generated by Django 4.2 on 2025-02-28 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_departament_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='main.section', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='section',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departament', to='main.departament', verbose_name='Цех'),
        ),
    ]
