# Generated by Django 4.2 on 2025-02-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_phone_section_alter_section_departament'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='home_41',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сотовый номер 1'),
        ),
        migrations.AddField(
            model_name='phone',
            name='home_42',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сотовый номер 2'),
        ),
        migrations.AddField(
            model_name='phone',
            name='home_43',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сотовый номер 3'),
        ),
    ]
