# Generated by Django 4.2 on 2025-02-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_phone_home_41_phone_home_42_phone_home_43'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'verbose_name': 'Цех', 'verbose_name_plural': '1.Цех'},
        ),
        migrations.AddField(
            model_name='phone',
            name='departament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.departament', verbose_name='Цех'),
        ),
        migrations.AddField(
            model_name='phone',
            name='home_vnut',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Домашний внутренний номер'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='home_41',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Домашний сотовый номер 1'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='home_42',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Домашний сотовый номер 2'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='home_43',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Домашний сотовый номер 3'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='main.section', verbose_name='Отдел'),
        ),
    ]
