# Generated by Django 4.2 on 2025-02-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_departament_options_phone_departament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='departament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.departament', verbose_name='Цех'),
        ),
    ]
