# Generated by Django 4.2 on 2025-02-28 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_phone_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='departament',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.departament', verbose_name='Цех'),
        ),
    ]
