# Generated by Django 4.2 on 2025-02-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_phone_departament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='departament',
        ),
    ]
