# Generated by Django 4.2 on 2025-03-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_phone_departament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='departament',
        ),
        migrations.AlterField(
            model_name='phone',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.section', verbose_name='Отдел'),
            preserve_default=False,
        ),
    ]
